# Generated by Django 4.2.4 on 2023-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='gst',
            field=models.FloatField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='service_charge',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
