# Generated by Django 4.2.4 on 2023-12-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathology.order')),
            ],
        ),
        migrations.CreateModel(
            name='report_file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_content', models.FileField(upload_to='report_files/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.report')),
            ],
        ),
    ]
