# Generated by Django 4.2.4 on 2023-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
    ]
