# Generated by Django 5.0.3 on 2024-04-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health_Campaign',
        ),
    ]
